#!/bin/bash
# ------------------------------------------------------------------
#
#     Scripts/spaceperc
#     Description: Script for piping the free space status into dzen
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

FREE=`df /home -h | awk 'END{gsub(/%/,""); print $5}'`

ICON="diskette.xbm"
if [[ $FREE -gt 90 ]]; then
    PERCBAR=`echo -e "$FREE"\
        | gdbar -bg darkgrey -fg red -h 5 -w 50`
else
    PERCBAR=`echo -e "$FREE"\
        | gdbar -bg darkgrey -fg white -h 5 -w 50`
fi

ICON='^i(/home/alex/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
echo "$ICON $PERCBAR"
