#!/hint/zsh

#-------------------------------------------------------------
# The 'ls' family (this assumes you use a recent GNU ls).
#-------------------------------------------------------------

# Use colors ($LS_COLORS) and human-readable sizes by default
# Also, use C locale for collation to avoid ignoring leading punctuation
# (when I name something `_tmp`, I want to order it before everything, dammit)
alias ls='LC_COLLATE=C.UTF-8 ls -h --color=auto'

alias lX='ls -lXB'         #  Sort by extension
alias lS='ls -lSr'         #  Sort by size, biggest last
alias lT='ls -ltr'         #  Sort by date, most recent last
alias lC='ls -ltcr'        #  Sort by/show change time,most recent last
alias lU='ls -ltur'        #  Sort by/show access time,most recent last
alias lV='ls -lV'          #  Sort by version, most recent last

# The ubiquitous 'll': directories first, with alphanumeric sorting
# XXX: was `ls -lv`, but it sorts case-sensitively
alias ll='ls -l --group-directories-first'

alias lr='ll -R'           #  Recursive ls
alias la='ll -A'           #  Show hidden files
alias laa='ll -a'           #  Show hidden files, and also . and ..
alias lv='ll -v'           #  Version-sort (see above)
alias l.='ll -d .*'        #  Show hidden files _only_
alias tree='tree -Csuh'    #  Nice alternative to 'recursive ls'

alias l='ll'               #  I'm lazy. Very lazy.
