#!/hint/zsh

function compalias() {
	local lhs=$1 rhs=$2 cmd=$2
	if (( ${+_comps[$cmd]} )); then
		compdef $lhs=$rhs
	fi
}

function compalias2() {
	local lhs=$1 rhs=( ${@:2} ) cmd=$2
	if (( ${+_comps[$cmd]} )); then
		local service=${_comps[$cmd]}
		local wrapped="_${lhs}"
		if [[ "${wrapped}" != "${(q)wrapped}" ]]; then
			print >&2 "compalias_ex($(-dump lhs rhs)): bad lhs"
			return 1
		fi
		eval "function ${wrapped}() {
			service=${(qq)cmd}
			words[1]=(${(@qq)rhs})
			(( CURRENT += $(($#rhs - 1)) ))
			${service}
		}"

		compdef $wrapped $lhs
	fi
}

compalias  duh		du
compalias  batman	man
compalias  vimman	man
compalias  qman		man

compalias  kmake	make
compalias  komake	make

compalias  rgc		rg
compalias  rgless	rg
compalias  rgo		rg

compalias  put		rsync
compalias  put-mv	rsync
compalias  put-sync	rsync
compalias  r-cput	rsync
compalias  r-put	rsync
compalias  r-sync-put	rsync

compalias  setfacl-d	setfacl

compalias  systemd-inhibit-auto	systemd-inhibit
compalias  systemd-inhibit-all	systemd-inhibit
compalias  systemd-nspawn-arch	systemd-nspawn

compalias  systemd-run-here	systemd-run
compalias  systemd-build-here	systemd-run

compalias  yt-dlpp	yt-dlp

compalias podman-arch	podman

compalias2 ccat		rg .
compalias  ccatp	rg

compalias  aria2cc      aria2c

if command -v mcli &>/dev/null; then
	complete -o nospace -C "$(command -v mcli)" mcli
fi
