#!/bin/zsh

#-------------------
# Personnal Aliases
#-------------------

alias mkdir='mkdir -pv'

alias ..='cd ..'
alias cd..='cd ..'

alias du='du -kh'    # Makes a more readable output.
alias df='df -kTh'

# Pretty-print of some PATH variables:
alias path='echo -e ${PATH//:/\\n}'
alias libpath='echo -e ${LD_LIBRARY_PATH//:/\\n}'

alias catconfig='grep -vE "^$|^ *(#|;)"'
alias fields='cut -d " " -f '

alias wget='wget -c'
alias bc='bc -l'
alias sha1='openssl sha1'
alias diff='colordiff'

alias r-cp-n='rsync -r --info=progress2 --human-readable --no-i-r'
alias r-cp='r-cp-n -a'
alias r-sync='r-cp --delete'

alias tar-i='tar --checkpoint=1000 --checkpoint-action=ttyout=%c'
alias tar-v='tar --checkpoint=1000 --checkpoint-action=ttyout=%c'
