#!/hint/zsh

#
# Personnal Aliases
#

alias mkdir='mkdir -pv'

alias ..='cd ..'
alias cd..='cd ..'

alias du='du -h'    # Makes a more readable output.
alias df='df -Th'

# Pretty-print of some PATH variables:
alias path='echo -e ${PATH//:/\\n}'
alias libpath='echo -e ${LD_LIBRARY_PATH//:/\\n}'

alias catconfig='grep -vE "^$|^ *(#|;)"'
alias fields='cut -d " " -f '

alias wget='wget -c'
alias bc='bc -l'
alias sha1='openssl sha1'
alias diff='colordiff'

alias r-cp-n='rsync -r --partial --no-i-r'
alias r-cp='r-cp-n -aHAX'
alias r-mv='r-cp --remove-source-files'
alias r-sync='r-cp --delete'
alias r-install='r-cp-n -rlEDH' # no perms (executability instead), times, group, owner, ACLs, xattrs

function cmake() {
	command cmake -G Ninja "$@"
}

function cmake-c() {
	cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ "$@"
}

function ccmake() {
	command ccmake -G Ninja "$@"
}

function ccmake-c() {
	ccmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ "$@"
}

function mkcd() {
	mkdir -pv "$1" && cd "$1"
}

function make() {
	if ! [[ -e GNUmakefile || -e Makefile || -e makefile ]]; then
		command make -f ~/bin/devel/Makefile "$@" # any -f given later in the command line will override this one
	else
		command make "$@"
	fi
}

function strip-color() {
	sed -r $'s/\x1b\x5b[[0-9;]+m//g'
}

function make_single_module() {
	local mod="$1"
	local dest="/usr/lib/modules/$(uname -r)/kernel/$mod.xz"
	make -j8 prepare modules_prepare
	make -j8 "$mod"
	xz -f -9 "$mod"
	sudo install -v -Dm644 "$mod.xz" "/usr/lib/modules/$(uname -r)/kernel/$mod.xz"
}
