#!/usr/bin/zsh

#
# bindings
#
zmodload zsh/terminfo
for keymap in viins vicmd; do
	bindkey  ${key[Up]} history-beginning-search-backward
	bindkey  ${key[Down]} history-beginning-search-forward
done
unset keymap
