#!/bin/zsh

#
# 1. Put terminal in the "application mode"
# so that binding kcuu1/kcud1 etc. will work
# (these terminfo entries are written for application mode).
#

function put_application_mode() {
	echoti smkx
}

function put_raw_mode() {
	echoti rmkx
}

zle -N zle-line-init put_application_mode
zle -N zle-line-finish put_raw_mode

bindkey -v

zmodload zsh/terminfo
for keymap in viins vicmd; do
	bindkey -M $keymap ${terminfo[khome]} beginning-of-line
	bindkey -M $keymap ${terminfo[kend]} end-of-line
	bindkey -M $keymap ${terminfo[kdch1]} vi-delete-char
done
