#!/bin/zsh

if (( IS_SOLARIZED )); then
	case "$TERM" in
	*-256color)
		# we don't want 256 colors, we have fine-tuned default colors (Solarized)
		export TERM="${TERM/256/16}"
		;;
	screen|xterm)
		# same
		export TERM=${TERM}-16color
		;;
	esac
	eval $(dircolors -b "$HOME/.solarized/dircolors/dircolors.ansi-universal")
	export MC_SKIN="$HOME/.solarized/mc/solarized.ini"

	ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=10
fi
