#!/bin/zsh

#
# Set the exact Solarized palette on VT
# Assume that even if not on VT, Solarized has been already configured
#
if [[ -t 2 ]]; then
#	if [[ "$TERM" == linux ]]; then
		cat <<-"EOF"
			]P8073642
			]P1dc322f
			]PA586e75
			]PB657b83
			]PC839496
			]PD6c71c4
			]PE93a1a1
			]PFfdf6e3
			]P2859900
			]P3b58900
			]P4268bd2
			]P5d33682
			]P62aa198
			]P7eee8d5
			]P0002b36
			]P9cb4b16
			[H[J
		EOF
#	fi
	export IS_SOLARIZED=1
fi

if (( IS_SOLARIZED )); then
	case "$TERM" in
	*-256color)
		# we don't want 256 colors, we have fine-tuned default colors (Solarized)
		export TERM="${TERM/256/16}"
		;;
	screen|xterm)
		# same
		export TERM=${TERM}-16color
		;;
	esac
	eval $(dircolors -b "$HOME/.dircolors-solarized")
	alias mc="mc -S solarized"

	ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=10
fi
