#!/hint/zsh

#
# completion settings
#
zstyle ':completion:*' auto-description 'argument: %d'
zstyle ':completion:*' completer _complete _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort name
zstyle ':completion:*' format '[%d]'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd ..
zstyle ':completion:*' insert-unambiguous false
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-prompt '%SAt $l (%p): Hit TAB for more, or the character to insert%s'
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]} r:|[-_./]=* r:|=*'
zstyle ':completion:*' max-errors 10 numeric
zstyle ':completion:*' menu select
zstyle ':completion:*' original true
zstyle ':completion:*' prompt '%e corrections made:'
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %l (%p)%s'
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*' special-dirs false
zstyle :compinstall filename '/home/intelfx/.zshrc'

zstyle ':completion:*' use-cache true
zstyle ':completion:*' cache-path "$(systemd-path user-state-cache)/zsh/zcompcache"
mkdir -p "$(systemd-path user-state-cache)/zsh/zcompcache"

autoload -Uz compinit
compinit -u # do not whine about ~/.zshrc/fpath in `sudo -s`

autoload -U +X bashcompinit
bashcompinit

if command -v mcli &>/dev/null; then
	complete -o nospace -C "$(command -v mcli)" mcli
fi
