#!/hint/zsh

#
# general settings
#
# Lines configured by zsh-newuser-install
HISTFILE=~/.history
HISTSIZE=2147483647
SAVEHIST=2147483647
setopt appendhistory autocd extendedglob dotglob nomatch histignoredups nocompletealiases autolist sharehistory
unsetopt beep notify bashautolist listambiguous
fpath=( "$HOME/.zsh/fpath" $fpath )
# End of lines configured by zsh-newuser-install
