#!/hint/zsh

#
# general settings
#
HISTFILE=~/.history
HISTSIZE=2147483647
SAVEHIST=2147483647

# History
setopt extendedhistory incappendhistory sharehistory histignoredups histverify histnostore histfcntllock
# Input/Output
setopt correct interactivecomments
# Changing Directories
setopt autocd
# Completion
setopt autolist automenu completealiases nobashautolist nolistambiguous # was nocompletealiases
# Expansion and Globbing
setopt extendedglob dotglob nomatch
# Zle
setopt nobeep
# Job Control
setopt nonotify

fpath=( "$HOME/.zsh/fpath" $fpath )
