#!/hint/zsh

#
# Reminder to myself how this works.
# We have two completion providers, fzf-provided scripts (hereinafter fzf.zsh) and fzf-tab.
#
# 1. Random commands -> fzf-tab
#    `$ random-command <Tab>` -> compsys + fzf-tab
#
# 2. Select commands -> fzf/completion.zsh (`**` is `$FZF_COMPLETION_TRIGGER`)
#    `$ vim **<Tab>` -> _fzf_compgen_path() (`$FZF_COMPLETION_OPTS`)
#    `$ cd **<Tab>` -> _fzf_compgen_dir() (`$FZF_COMPLETION_OPTS`)
#    ...
#
# 3. Special Vi mode key combinations -> fzf/key-bindings.zsh
#    `/` -> `fzf-history-widget` (`$FZF_CTRL_R_OPTS`)
#           NB: relevance sorting is still `^R` because it is hardcoded in the widget!
#    `C` -> `fzf-cd-widget` (`$FZF_ALT_C_COMMAND`, `$FZF_ALT_C_OPTS`)
#    `^T` -> `fzf-file-widget` (`$FZF_CTRL_T_COMMAND`, `$FZF_CTRL_T_OPTS`)
#
# 4. Command-line usage: see `$FZF_DEFAULT_COMMAND`
#
# 5. All of the above: see `$FZF_DEFAULT_OPTS`
#

if ! [[ -d /usr/share/fzf ]]; then
	return
fi

source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

#
# Configure fzf-tab
#

zstyle ':fzf-tab:*' switch-group 'alt-1' 'alt-2'
zstyle ':fzf-tab:*' query-string input
if [[ $TMUX ]]; then
	zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
fi

#
# Set up behavior for fzf.zsh
#

# Options to fzf command
export FZF_COMPLETION_OPTS='
--border
--info=inline
--bind=ctrl-space:toggle
'

if command -v fd &>/dev/null; then
	# Use fd (https://github.com/sharkdp/fd) instead of the default find
	# command for listing path candidates.
	# - The first argument to the function ($1) is the base path to start traversal
	# - See the source code (completion.{bash,zsh}) for the details.
	_fzf_compgen_path() {
		fd --hidden --follow --exclude ".git" . "$1"
	}

	# Use fd to generate the list for directory completion
	_fzf_compgen_dir() {
		fd --type d --hidden --follow --exclude ".git" . "$1"
	}
fi

#
# Set up custom keybindings for fzf.zsh widgets
#

# Use zsh Normal Mode + / (reverse-i-search, vi-history-search-backward) to use fzf instead
# (likewise for Normal Mode + ?)
bindkey -M vicmd '/' fzf-history-widget
bindkey -M vicmd '?' fzf-history-widget
# Do not interpret Insert Mode + ESC + [/,] as _history-complete-* as it conflicts with normal Vi mode usage
bindkey -M viins -r '^[/'
bindkey -M viins -r '^[,'

# Do not interpret ESC + c as fzf-cd-widget as it conflicts with normal Vi mode usage
bindkey -M vicmd -r '^[c'
bindkey -M viins -r '^[c'
# Instead, use zsh Normal Mode + C (capital)
bindkey -M vicmd 'C' fzf-cd-widget

#
# Clever hack: set up double <Tab> instead of $FZF_COMPLETION_TRIGGER for fzf.zsh
# NOTE: this needs fzf-tab to load before this file, read below
#

# Another reminder for myself how this all works.
#
# Both fzf-tab and fzf/completion.zsh (hereinafter fzf.zsh) bind their widgets
# to ^I (Tab) and wrap the previously bound widget.
#
# fzf-tab manual advises the user to load fzf-tab last (specifically, after
# fzf.zsh) such that fzf-tab's widget (fzf-tab-complete) is called first and
# wraps the fzf.zsh's widget (fzf-complete).
#
# However, due to my double <Tab> hack I would prefer if the order was reversed,
# such that fzf.zsh's widget is called first and wraps the fzf-tab's widget
# (fzf-tab-complete).
#
# The reason for this is that if I use a double <Tab> and fzf-complete fails to
# come up with a completion, it will call the next wrapped widget, which has to
# be fzf-tab-complete so that I still get some sort of fzf-powered completion
# instead of expand-or-complete (the default one).
# (Also see the comment below.)

fzf-completion-notrigger() {
	# disable trigger just this once
	local FZF_COMPLETION_TRIGGER=""
	# if fzf-completion can't come up with something, call fzf-tab-complete
	# instead of the default completion widget (expand-or-complete).
	#
	# FIXME: triggers an infinite recursion on an empty prompt
	#        if this worked, the above ordering dance would not be needed
	# _zsh_autosuggest_highlight_reset:3: maximum nested function level reached; increase FUNCNEST?
	#
	#local fzf_default_completion='fzf-tab-complete'
	fzf-completion "$@"
}
zle -N fzf-completion-notrigger

# Set an aggressive $KEYTIMEOUT to make usage of single <Tab> less miserable
KEYTIMEOUT=20
# Bind double <Tab>
bindkey '\t\t' fzf-completion-notrigger
# Bind Ctrl-Space in case I am unable to use double <Tab> due to a combination
# of the aggressive $KEYTIMEOUT on a slow link.
bindkey '^ ' fzf-completion-notrigger
