# general settings
alang=eng,en
slang=eng,en
screenshot-directory=~/Pictures/mpv

osd-fractions
term-osd-bar

# disable normal OSD for uosc
osd-bar=no
border=no

# avoid potentially unbounded runtime with no user feedback (in form of window)
# while the file is being loaded
# (NOTE: this does not work in a profile)
# XXX: mpv-player/mpv#17641
#force-window=immediate

# implemented as autosave.lua
#save-position-on-quit=yes
# TODO: write some sort of smart resume GUI dialog
resume-playback=yes
resume-playback-check-mtime=yes

# sane defaults
ao=pipewire
vo=gpu-next
hwdec=vaapi
hwdec-codecs=all
gpu-context=waylandvk
# vulkan-device=... (see mpv-private.conf)

# misc special globals
opengl-pbo
target-colorspace-hint=auto
target-colorspace-hint-mode=target

# no VP9: [vcodec!=?vp9]
# no AV1: [vcodec!*=?av01]
ytdl-format=bestvideo*[width<=?2560][height<=?1600][fps<=?60]+bestaudio/best
ytdl-raw-options=cookies=~/.netcookies,sub-lang="en",write-sub=,write-auto-sub=
sub-auto=fuzzy

cache-secs=60
demuxer-readahead-secs=60
demuxer-hysteresis-secs=10
demuxer-max-bytes=512MiB
demuxer-max-back-bytes=512MiB

# make life easier on crappy network filesystems
stream-buffer-size=1MiB

# https://www.notebookcheck.net/Lenovo-ThinkPad-X1-Carbon-2018-matte-WQHD-i7-Laptop-Review.396706.0.html
# -> ~/.local/share/icc/LP140QH2_SPB1_03.icm
# https://www.notebookcheck.net/Lenovo-ThinkPad-P1-Gen-7-review-Without-TrackPoint-buttons-with-Nvidia-GeForce-RTX-4060.901578.0.html
# -> ~/.local/share/icc/LEN41B0_.icm
# icc-profile=... # does not work in Wayland yet
# target-peak=... # makes no sense in SDR environment

# replacement for HTTP basic auth:
# mpv-private.conf:
# 	user-agent=libmpv/XXX
# nginx.conf:
# 	map $http_user_agent $myhostname_auth_basic {
# 		"libmpv/XXX" "off";
# 		default      "myhostname";
# 	}
# 	server {
# 		location ... {
# 			auth_basic $myhostname_auth_basic;
# 			auth_basic_user_file ...;
# 		}
# 	}
include=~/.config/mpv/mpv-private.conf
