#!/hint/zsh

#
# Set the exact Solarized palette on VT
#

# WSL terminals don't play nice with ESC ] P
# If under WSL, assume Solarized has been configured
if [[ "$WSLENV" ]]; then
	export IS_SOLARIZED=1
	return
fi

# If not on VT, assume Solarized has been configured
if [[ "$TERM" != linux && "$TERM" != vt* ]]; then
	export IS_SOLARIZED=1
	return
fi

cat <<-"EOF"
	]R
	]P0073642
	]P1dc322f
	]P2859900
	]P3b58900
	]P4268bd2
	]P5d33682
	]P62aa198
	]P7eee8d5
	]P8002b36
	]P9cb4b16
	]PA586e75
	]PB657b83
	]PC839496
	]PD6c71c4
	]PE93a1a1
	]PFfdf6e3
	[H[J
EOF
#
#	[0;100;94m
#	[8]
#	[1;12]
#	[2;12]
#
export IS_SOLARIZED=1
