#!/hint/zsh

#
# Make sure zsh (& everything else) know about at least 16 colors
#

if  (( ${termcap[Co]-0} > 0 && ${termcap[Co]-0} < 16 )) \
&& ( TERM="${TERM}-16color"; (( ${termcap[Co]-0} >= 16 )) ); then
	export TERM="${TERM}-16color"
fi

#
# Set the exact Solarized palette on VT
#

# WSL terminals don't play nice with ESC ] P
# If under WSL, assume Solarized has been configured
if [[ "$WSLENV" ]]; then
	export IS_SOLARIZED=1
	return
fi

# If not on VT, assume Solarized has been configured
if [[ "$TERM" != linux* && "$TERM" != vt* ]]; then
	export IS_SOLARIZED=1
	return
fi

if [[ $1 == reset ]]; then
	# Default: fg=7, bg=0
	# Underline: fg=15 (bright)
	# Dim: fg=8 (dim)
	cat <<-"EOF" | tr -d ' \t\n'
		]R
		[0;37;40m
		[1;15]
		[2;8]
		[8]
		[J
	EOF
	return
fi

cat <<-"EOF" | tr -d ' \t\n'
	]R
	]P0073642
	]P1dc322f
	]P2859900
	]P3b58900
	]P4268bd2
	]P5d33682
	]P62aa198
	]P7eee8d5
	]P8002b36
	]P9cb4b16
	]PA586e75
	]PB657b83
	]PC839496
	]PD6c71c4
	]PE93a1a1
	]PFfdf6e3
	[0m
	[0;5;94;100m
	[8]
	[1;12]
	[2;12]
	[J
EOF
#
#	]R
#		resets terminal
#	]Pnaabbcc
#		sets ANSI color <0xn> to r=<0xaa>, g=<0xbb>, b=<0xcc>
#	[0;5;100;94m
#		sets background and foreground to base03/base00:
#			0: reset attributes
#			94: fg=bright,4 (== 12)
#			100: bg=bright,0 (== 8)
#			     this is broken in Linux VT (100+n is the same as 40+n), still done this way for symmetry
#			5: blink <=> bg=bright (sic!)
#			   XXX: bright background colors only work with 256-glyph fonts
#			        (notably, ter-vXXn are out!)
#	[1;12]
#	[2;12]
#		sets dim and underline foreground to base00 (same as normal)
#	[8]
#		sets current attributes as default
#	[H[J
#		resets cursor position
#
export IS_SOLARIZED=1
