[registries.crates-io]
protocol = 'git'

#[build]
#rustflags = [
#]

[profile.dev]
opt-level = 0
lto = false
incremental = true
debug = 2

[profile.release]
debug = false
strip = true
opt-level = 3
#lto = "fat"

#[target.x86_64-unknown-linux-gnu]
#[target.i686-unknown-linux-gnu]
#[target.'cfg(all())']
#linker = "clang"
#rustflags = [
#	"-C", "link-arg=-fuse-ld=lld",
#]

#[env]
#CC = "clang"
#CXX = "clang++"
#CFLAGS = "-fuse-ld=lld"
#CXXFLAGS = "-fuse-ld=lld"
#LDFLAGS = "-fuse-ld=lld"
