[registries.crates-io]
protocol = 'git'

[build]
rustflags = [
	#"-Z", "threads=8",
]

[profile.dev]
opt-level = 0
lto = false
incremental = true
debug = 2

[profile.release]
debug = false
strip = true
opt-level = 3

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
	"-C", "target-cpu=native",
	"-C", "link-arg=-fuse-ld=lld",
]

[env]
CC = "clang"
CXX = "clang++"
