 local menubeceed89e397495003f6ff5a4d895d66 = {
     {"Amarok", "amarok ", "/usr/share/icons/hicolor/16x16/apps/amarok.png" },
     {"Audacity", "audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Cantata", "cantata "},
     {"Guitar Pro 6", "/opt/GuitarPro6/launcher.sh", "/usr/share/pixmaps/guitarpro6.png" },
     {"K3b", "k3b ", "/usr/share/icons/hicolor/16x16/apps/k3b.png" },
     {"Kdenlive", "kdenlive  -caption \"Kdenlive\" ", "/usr/share/icons/hicolor/32x32/apps/kdenlive.png" },
     {"PulseAudio Manager", "paman", "/usr/share/icons/gnome/16x16/devices/audio-card.png" },
     {"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share/icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"SMPlayer", "smplayer ", "/usr/share/icons/hicolor/16x16/apps/smplayer.png" },
     {"V4L2-UCP", "v4l2ucp", "///usr/share/icons/v4l2ucp.png" },
     {"avidemux (QT)", "avidemux2_qt4", "/usr/share/pixmaps/avidemux.png" },
     {"puddletag", "puddletag ", "/usr/share/pixmaps/puddletag.png" },
     {"soundKonverter", "soundkonverter ", "/usr/share/icons/hicolor/16x16/apps/soundkonverter.png" },
     {"Медиаплеер VLC", "/usr/bin/vlc ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"Микшер FFADO", "ffado-mixer"},
 }

 local menu9a1dcda9efe2bfc3963e75f98cc1ffd5 = {
     {"FontForge", "fontforge ", "/usr/share/icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU Image Manipulation Program", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gwenview", "gwenview  -caption \"Gwenview\" ", "/usr/share/icons/hicolor/16x16/apps/gwenview.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/inkscape.png" },
     {"KColorChooser", "kcolorchooser", "/usr/share/icons/hicolor/16x16/apps/kcolorchooser.png" },
     {"KRuler", "kruler", "/usr/share/icons/hicolor/16x16/apps/kruler.png" },
     {"KSnapshot", "ksnapshot -caption \"KSnapshot\"", "/usr/share/icons/hicolor/16x16/apps/ksnapshot.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Mirage", "mirage ", "/usr/share/pixmaps/mirage.png" },
     {"Okular", "okular   -caption \"Okular\"", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Panorama", "panoramagui  -caption Panorama ", "/usr/share/icons/hicolor/16x16/actions/panorama.png" },
     {"Photo Layouts Editor", "photolayoutseditor", "/usr/share/icons/hicolor/16x16/apps/photolayoutseditor.png" },
     {"XSane - Scanning", "xsane", "/usr/share/pixmaps/xsane.xpm" },
     {"digiKam", "digikam -caption digiKam ", "/usr/share/icons/hicolor/16x16/apps/digikam.png" },
     {"gbdfed", "gbdfed ", "/usr/share/pixmaps/gbdfed.png" },
     {"showFoto", "showfoto  -caption showFoto ", "/usr/share/icons/hicolor/16x16/apps/showfoto.png" },
     {"Преобразование в DNG", "dngconverter  -caption DNGConverter ", "/usr/share/icons/hicolor/16x16/apps/dngconverter.png" },
     {"Сканирование изображений", "scangui  -caption AcquireImages ", "/usr/share/icons/gnome/16x16/devices/scanner.png" },
     {"Смешивание экспозиции", "expoblending  -caption ExpoBlending ", "/usr/share/icons/hicolor/16x16/actions/expoblending.png" },
 }

 local menu9450b445fe92072aefd60520dcc39900 = {
     {"Endgame: Singularity", "/usr/bin/singularity", "///usr/share/singularity/data/images/icon.png" },
     {"Liquid War", "liquidwar", "/usr/share/pixmaps/liquidwar.xpm" },
     {"Polynomial", "polynomial-free", "///usr/share/pixmaps/polynomial-free.png" },
     {"Powder Toy", "/usr/bin/powder-toy", "/usr/share/pixmaps/powder-toy.png" },
     {"Xmoto", "xmoto", "/usr/share/pixmaps/xmoto.xpm" },
 }

 local menu25385e702800d748c19cf6ea4f5811ec = {
     {"Akregator", "akregator  -caption \"Akregator\"", "/usr/share/icons/hicolor/16x16/apps/akregator.png" },
     {"BlueDevil", "bluedevil-monolithic"},
     {"Dropbox", "dropboxd", "/usr/share/pixmaps/dropbox.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share/icons/gnome/16x16/mimetypes/html.png" },
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome", "/opt/google/chrome/google-chrome --audio-buffer-size=2048 --ignore-gpu-blocklist ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"Google Chrome", "/opt/google/chrome/google-chrome ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
     {"KGet", "kget -caption \"KGet\"  ", "/usr/share/icons/hicolor/16x16/apps/kget.png" },
     {"KMail", "kmail -caption \"KMail\" ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KPPP", "kppp", "/usr/share/icons/hicolor/16x16/apps/kppp.png" },
     {"KRDC", "krdc -caption \"KRDC\" "},
     {"KTorrent", "ktorrent  -caption \"KTorrent\" ", "/usr/share/icons/hicolor/16x16/apps/ktorrent.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Konversation", "konversation -caption \"Konversation\" ", "/usr/share/icons/hicolor/16x16/apps/konversation.png" },
     {"Kopete", "kopete -caption \"Kopete\" ", "/usr/share/icons/hicolor/16x16/apps/kopete.png" },
     {"Krfb", "krfb -caption \"Krfb\" ", "/usr/share/icons/gnome/16x16/apps/krfb.png" },
     {"Rekonq", "rekonq ", "/usr/share/icons/hicolor/16x16/apps/rekonq.png" },
     {"Skype", "skype ", "/usr/share/icons/hicolor/16x16/apps/skype.png" },
     {"TeamViewer 8", "/opt/teamviewer8/tv_bin/script/teamviewer", "///opt/teamviewer8/tv_bin/desktop/teamviewer.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"aLinkCreator", "alc", "/usr/share/pixmaps/alc.xpm" },
     {"aMule", "amule", "/usr/share/pixmaps/amule.xpm" },
     {"aMuleGUI", "amulegui", "/usr/share/pixmaps/amulegui.xpm" },
     {"wxCas", "wxcas", "/usr/share/pixmaps/wxcas.xpm" },
     {"Мастер импорта", "importwizard", "/usr/share/icons/hicolor/64x64/apps/kontact-import-wizard.png" },
     {"Навигатор Avahi по серверам SSH", "/usr/bin/bssh", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Навигатор Avahi по серверам VNC", "/usr/bin/bvnc", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
 }

 local menu2b5388b53284d5e447898c5aad293da4 = {
     {"Celestia", "celestia", "/usr/share/pixmaps/celestia.png" },
     {"QtiPlot", "qtiplot", "///usr/share/pixmaps/qtiplot.png" },
 }

 local menud26c1170c5110a4264a8a8a89ec20529 = {
     {"Avogadro", "avogadro ", "/usr/share/pixmaps/avogadro-icon.png" },
     {"Cantor", "cantor  -caption \"Cantor\"", "/usr/share/icons/hicolor/16x16/apps/cantor.png" },
     {"GeoGebra 5.0 Beta", "geogebra5-beta ", "/usr/share/icons/hicolor/16x16/apps/geogebra5-beta.png" },
     {"GeoGebra 5.0 Beta-JOGL1", "geogebra5-beta-jogl1 ", "/usr/share/icons/hicolor/16x16/apps/geogebra5-beta.png" },
     {"KAlgebra", "kalgebra", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
     {"Kalzium", "kalzium -caption \"Kalzium\" ", "/usr/share/icons/hicolor/16x16/apps/kalzium.png" },
     {"KmPlot", "kmplot", "/usr/share/icons/hicolor/16x16/apps/kmplot.png" },
     {"Marble", "marble", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Мобильная KAlgebra", "kalgebramobile", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
 }

 local menu8caf0567988f6898bf53e8c848c6f7bc = {
     {"KAddressBook", "kaddressbook ", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"KMail", "kmail -caption \"KMail\" ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KOrganizer", "korganizer ", "/usr/share/icons/hicolor/16x16/apps/korganizer.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"Kontact", "kontact", "/usr/share/icons/hicolor/16x16/apps/kontact.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Lokalize", "lokalize  -caption \"Lokalize\"", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Okular", "okular   -caption \"Okular\"", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Мастер импорта", "importwizard", "/usr/share/icons/hicolor/64x64/apps/kontact-import-wizard.png" },
 }

 local menu8b25bc71fce7a929a6124e9354c07cdb = {
     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Cola Git GUI", "git-cola --prompt", "///usr/share/git-cola/icons/git.svg" },
     {"Eclipse", "eclipse"},
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/16x16/apps/fluid.png" },
     {"Git DAG", "git-dag --prompt", "///usr/share/git-cola/icons/git.svg" },
     {"KAppTemplate", "kapptemplate", "/usr/share/icons/hicolor/16x16/apps/kapptemplate.png" },
     {"KCachegrind", "kcachegrind -caption \"KCachegrind\" ", "/usr/share/icons/hicolor/32x32/apps/kcachegrind.png" },
     {"KDbg", "kdbg -caption \"KDbg\" "},
     {"KDevelop 4", "kdevelop "},
     {"KDevelop 4 (Pick Session)", "kdevelop --ps"},
     {"KUIViewer", "kuiviewer -caption \"KUIViewer\"", "/usr/share/icons/hicolor/16x16/apps/kuiviewer.png" },
     {"Kompare", "kompare -caption \"Kompare\" -o ", "/usr/share/icons/hicolor/16x16/apps/kompare.png" },
     {"Lokalize", "lokalize  -caption \"Lokalize\"", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"NepSaK - The Nepomuk Shell", "nepomukshell"},
     {"OpenJDK Monitoring & Management Console", "/usr/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "/usr/bin/policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"Qt4 Assistant ", "assistant-qt4", "/usr/share/icons/hicolor/32x32/apps/assistant-qt4.png" },
     {"Qt4 Designer", "designer-qt4", "/usr/share/icons/hicolor/128x128/apps/designer-qt4.png" },
     {"Qt4 Linguist ", "linguist-qt4", "/usr/share/icons/hicolor/16x16/apps/linguist-qt4.png" },
     {"Qt4 QDbusViewer ", "qdbusviewer-qt4", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer-qt4.png" },
     {"gitg", "gitg ", "/usr/share/icons/hicolor/16x16/apps/gitg.png" },
     {"Консоль Akonadi", "akonadiconsole", "/usr/share/icons/hicolor/16x16/apps/akonadiconsole.png" },
 }

 local menu0ffe722bca4921a22484918551d22d36 = {
     {"TigerVNC viewer", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
 }

 local menu13155df48f218a078bb8bdc9649e5b20 = {
     {"Dolphin", "dolphin  -caption \"Dolphin\" ", "/usr/share/icons/gnome/16x16/apps/system-file-manager.png" },
     {"GParted", "/usr/bin/gparted_polkit ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"K3b", "k3b ", "/usr/share/icons/hicolor/16x16/apps/k3b.png" },
     {"KDiskFree", "kdf -caption \"KDiskFree\"", "/usr/share/icons/hicolor/16x16/apps/kdf.png" },
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption \"KSystemLog\""},
     {"KUser", "xdg_menu_su kuser  -caption \"KUser\"", "/usr/share/icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Krfb", "krfb -caption \"Krfb\" ", "/usr/share/icons/gnome/16x16/apps/krfb.png" },
     {"KwikDisk", "kwikdisk -caption \"KwikDisk\"", "/usr/share/icons/hicolor/16x16/apps/kwikdisk.png" },
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Yakuake", "yakuake", "/usr/share/icons/hicolor/16x16/apps/yakuake.png" },
     {"urxvt", "urxvt", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (client)", "urxvtc", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"urxvt (tabbed)", "urxvt-tabbed", "/usr/share/icons/gnome/16x16/apps/utilities-terminal.png" },
     {"Настройка печати", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Обозреватель Avahi Zeroconf", "/usr/bin/avahi-discover", "/usr/share/icons/gnome/16x16/devices/network-wired.png" },
     {"Очиститель Nepomuk", "nepomukcleaner"},
     {"Редактор dconf", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"Резервное копирование Nepomuk", "nepomukbackup"},
     {"Системный монитор", "ksysguard ", "/usr/share/icons/gnome/16x16/apps/utilities-system-monitor.png" },
     {"Управление индексированием файлов в Nepomuk", "nepomukcontroller"},
 }

 local menu91af6ed4e0be6a48ab48ec8b6e768568 = {
     {"7-Zip FM", "7zFM", "/usr/share/icons/hicolor/32x32/apps/p7zip.png" },
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Ark", "ark -caption \"Ark\" ", "/usr/share/icons/hicolor/16x16/apps/ark.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"KAlarm", "kalarm -caption \"KAlarm\" ", "/usr/share/icons/hicolor/16x16/apps/kalarm.png" },
     {"KCalc", "kcalc -caption \"KCalc\"", "/usr/share/icons/gnome/16x16/apps/accessories-calculator.png" },
     {"KCharSelect", "kcharselect -caption \"KCharSelect\"", "/usr/share/icons/gnome/16x16/apps/accessories-character-map.png" },
     {"KFloppy", "kfloppy -caption \"KFloppy\"", "/usr/share/icons/hicolor/16x16/apps/kfloppy.png" },
     {"KGpg", "kgpg ", "/usr/share/icons/hicolor/16x16/apps/kgpg.png" },
     {"KNotes", "knotes", "/usr/share/icons/hicolor/16x16/apps/knotes.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTimer", "ktimer", "/usr/share/icons/hicolor/16x16/apps/ktimer.png" },
     {"KWrite", "kwrite ", "/usr/share/icons/gnome/16x16/apps/accessories-text-editor.png" },
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Kleopatra", "kleopatra", "/usr/share/icons/hicolor/16x16/apps/kleopatra.png" },
     {"Okteta", "okteta -caption \"Okteta\" ", "/usr/share/icons/hicolor/16x16/apps/okteta.png" },
     {"Sweeper", "sweeper"},
     {"compton", "compton"},
     {"synaptiks", "synaptiks"},
 }

xdgmenu = {
    {"Аудио и видео", menubeceed89e397495003f6ff5a4d895d66},
    {"Графика", menu9a1dcda9efe2bfc3963e75f98cc1ffd5},
    {"Игры", menu9450b445fe92072aefd60520dcc39900},
    {"Интернет", menu25385e702800d748c19cf6ea4f5811ec},
    {"Научные и математические", menu2b5388b53284d5e447898c5aad293da4},
    {"Образовательные", menud26c1170c5110a4264a8a8a89ec20529},
    {"Офис", menu8caf0567988f6898bf53e8c848c6f7bc},
    {"Программирование", menu8b25bc71fce7a929a6124e9354c07cdb},
    {"Прочие", menu0ffe722bca4921a22484918551d22d36},
    {"Системные", menu13155df48f218a078bb8bdc9649e5b20},
    {"Стандартные", menu91af6ed4e0be6a48ab48ec8b6e768568},
}

